Correction de la sélection d'une nouvelle semaine dans Planning.vue + préparation du controller permettant de re-calculer les compteurs + ajout du debug PHP

diff --git a/api-server/Dockerfile b/api-server/Dockerfile
--- a/api-server/Dockerfile
+++ b/api-server/Dockerfile
@@ -1,24 +1,36 @@
 ## COMMON (pour déveloper, on utilise ce stage)
-# FROM php:7.3.22-cli-alpine3.12
-FROM php:7.3-cli-alpine as common-stage
+FROM php:7.3-cli-buster as common-stage
 
 # Installation de Composer en suivant https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
-RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --version=1.10.10 --install-dir=/usr/local/bin --filename=composer
-
+RUN apt update && apt install -y git wget \
+ && wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --version=1.10.20 --install-dir=/usr/local/bin --filename=composer \
 # Installation de Symfony en suivant https://symfony.com/download
-RUN apk --no-cache add bash git && wget https://get.symfony.com/cli/installer -O - | bash
-RUN mv $HOME/.symfony/bin/symfony /usr/local/bin/symfony
+ && wget https://get.symfony.com/cli/installer -O - | bash \
+ && mv $HOME/.symfony/bin/symfony /usr/local/bin/symfony
 
 # Configurations PHP pour l'application
-RUN apk --no-cache add mysql-dev \
+RUN apt update && apt install -y libmariadb-dev \
  && docker-php-ext-install pdo_mysql
 RUN sed -i 's/;extension=sodium/extension=sodium/' /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini-development \
  && sed -i 's/;extension=intl/extension=intl/' /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini-development \
- && sed -i 's/memory_limit = 128M/memory_limit = 512M/' /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini-development \
+ && sed -i -E 's/^;?memory_limit.*/memory_limit = 512M/' /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini-development \
  && sed -i 's/post_max_size = 8M/post_max_size = 130M/' /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini-development \
  && sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 128M/' /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini-development
 
 WORKDIR /api-server
+
+## DEV
+FROM common-stage as dev-stage
+
+ARG XDEBUG_VERSION=3.0.2
+RUN set -eux; \
+  apt update; apt install -y netcat; \
+  pecl install xdebug-$XDEBUG_VERSION; \
+  docker-php-ext-enable xdebug;
+RUN \
+  echo "error_reporting = E_ALL" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
+  echo "display_startup_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
+  echo "display_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini;
 
 ## BUILD
 FROM common-stage as build-stage
@@ -40,8 +52,8 @@ RUN php bin/console cache:clear
 FROM php:7.3-apache as run-stage
 
 RUN apt update && apt full-upgrade -y \
- && apt install -y libpq-dev \
- && docker-php-ext-install pdo_pgsql \
+ && apt install -y libmariadb-dev \
+ && docker-php-ext-install pdo_mysql \
  && sed -i 's|/var/www/html|/var/www/html/public|' /etc/apache2/sites-available/000-default.conf \
  && a2enmod rewrite
 
